### ISSUE TITLE
how to train a model in bcss dataset

### ISSUE THREAD

**Issue by shuaijun-36** [HHHedo/SGCL#1]
how to preprocess bcss dataset and train a segmentation model on it?

**Comment by shuaijun-36** [comment]
there is no dataset preparation for bcss dataset in [https://github.com/WXinlong/mmsegmentation/blob/master/docs/dataset_prepare.md](url) could you please provide a more detailed example?

**Comment by Carboxy** [comment]
We apologize for missing some necessary examples. Now we have updated the code to prepare the bcss dataset at tools/prepare_data/prepare_bcss. First, run "make_patches.py" to make patches. Second, run "group_mask.py" to map "region classes" to "broad categories", referring to [https://academic.oup.com/bioinformatics/article/35/18/3461/5307750#supplementary-data](url).
